apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-application-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - unikorn-cloud.org
  resources:
  - helmapplications
  verbs:
  - list
  - watch
- apiGroups:
  - application.unikorn-cloud.org
  resources:
  - applicationsets
  verbs:
  - list
  - watch
  - create
  - update
  - delete
# Find project namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - list
  - watch
