apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-application-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - unikorn-cloud.org
  resources:
  - applications
  verbs:
  - list
  - watch
# Find project namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
