apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-application-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage applicationsets (my job).
- apiGroups:
  - application.unikorn-cloud.org
  resources:
  - applicationsets
  verbs:
  - list
  - watch
  - update
# Manage applicationsets (my job).
- apiGroups:
  - application.unikorn-cloud.org
  resources:
  - applicationsets/status
  verbs:
  - update
# Get Kubernetes clusters so we can provision applications on it.
- apiGroups:
  - unikorn-cloud.org
  resources:
  - helmapplications
  - kubernetesclusters
  - clustermanagers
  verbs:
  - list
  - watch
# ArgoCD integration.
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - list
  - get
  - watch
  - patch
  - delete
# ArgoCD integration (access to API secret).
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
