apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unikorn-application-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Controller prerequisites.
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
